import { Link } from "react-router-dom";
import Footer from "../Footer/Footer";
import { useEffect, useState } from "react";
import NavSecEn from "../NavSecEn/NavSecEn";
import SubNav from "../subNav/subNav";



export default function PrivacyPolicy() {



    useEffect(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }, [])

    return <>

        <SubNav />

        <div id="PrivacyPolicy" className="px-10 py-20 text-xl">

            <div className="backHome mb-10 text-lg  text-gray-400 dir-ltr">
                <span> <Link to={"/"} className="hover:text-gray-800 transition-colors"> Home </Link> |  Privacy Policy </span>
            </div>

            <div><p dir="ltr" className="font-bold">Privacy Policy  </p>

                <p dir="ltr">==============</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Last updated: December 25, 2023</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">This Privacy Policy describes Our policies and procedures on the collection,</p>
                <p dir="ltr">use and disclosure of Your information when You use the Service and tells You</p>
                <p dir="ltr">about Your privacy rights and how the law protects You.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We use Your Personal data to provide and improve the Service. By using the</p>
                <p dir="ltr">Service, You agree to the collection and use of information in accordance with</p>
                <p dir="ltr">this Privacy Policy. This Privacy Policy has been created with the help of the</p>
                <p dir="ltr">[Privacy Policy Generator](https://www.termsfeed.com/privacy-policy-</p>
                <p dir="ltr">generator/).</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Interpretation and Definitions  </p>
                <p dir="ltr">------------------------------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Interpretation  </p>
                <p dir="ltr">~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The words of which the initial letter is capitalized have meanings defined</p>
                <p dir="ltr">under the following conditions. The following definitions shall have the same</p>
                <p dir="ltr">meaning regardless of whether they appear in singular or in plural.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Definitions  </p>
                <p dir="ltr">~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">For the purposes of this Privacy Policy:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Account means a unique account created for You to access our Service or</p>
                <p dir="ltr">    parts of our Service.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Affiliate means an entity that controls, is controlled by or is under</p>
                <p dir="ltr">    common control with a party, where "control" means ownership of 50% or</p>
                <p dir="ltr">    more of the shares, equity interest or other securities entitled to vote</p>
                <p dir="ltr">    for election of directors or other managing authority.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Company (referred to as either "the Company", "We", "Us" or "Our" in this</p>
                <p dir="ltr">    Agreement) refers to Km Agency LLC, 1207 Delaware Avenue, Wilmington, DE</p>
                <p dir="ltr">    19806.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Cookies are small files that are placed on Your computer, mobile device or</p>
                <p dir="ltr">    any other device by a website, containing the details of Your browsing</p>
                <p dir="ltr">    history on that website among its many uses.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Country refers to: Delaware, United States</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Device means any device that can access the Service such as a computer, a</p>
                <p dir="ltr">    cellphone or a digital tablet.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Personal Data is any information that relates to an identified or</p>
                <p dir="ltr">    identifiable individual.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Service refers to the Website.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Service Provider means any natural or legal person who processes the data</p>
                <p dir="ltr">    on behalf of the Company. It refers to third-party companies or</p>
                <p dir="ltr">    individuals employed by the Company to facilitate the Service, to provide</p>
                <p dir="ltr">    the Service on behalf of the Company, to perform services related to the</p>
                <p dir="ltr">    Service or to assist the Company in analyzing how the Service is used.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Usage Data refers to data collected automatically, either generated by the</p>
                <p dir="ltr">    use of the Service or from the Service infrastructure itself (for example,</p>
                <p dir="ltr">    the duration of a page visit).</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * You means the individual accessing or using the Service, or the company,</p>
                <p dir="ltr">    or other legal entity on behalf of which such individual is accessing or</p>
                <p dir="ltr">    using the Service, as applicable.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Collecting and Using Your Personal Data  </p>
                <p dir="ltr">---------------------------------------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Types of Data Collected  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Personal Data  </p>
                <p dir="ltr">*************</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">While using Our Service, We may ask You to provide Us with certain personally</p>
                <p dir="ltr">identifiable information that can be used to contact or identify You.</p>
                <p dir="ltr">Personally identifiable information may include, but is not limited to:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Email address</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * First name and last name</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Usage Data</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Usage Data  </p>
                <p dir="ltr">**********</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Usage Data is collected automatically when using the Service.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Usage Data may include information such as Your Device's Internet Protocol</p>
                <p dir="ltr">address (e.g. IP address), browser type, browser version, the pages of our</p>
                <p dir="ltr">Service that You visit, the time and date of Your visit, the time spent on</p>
                <p dir="ltr">those pages, unique device identifiers and other diagnostic data.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">When You access the Service by or through a mobile device, We may collect</p>
                <p dir="ltr">certain information automatically, including, but not limited to, the type of</p>
                <p dir="ltr">mobile device You use, Your mobile device unique ID, the IP address of Your</p>
                <p dir="ltr">mobile device, Your mobile operating system, the type of mobile Internet</p>
                <p dir="ltr">browser You use, unique device identifiers and other diagnostic data.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We may also collect information that Your browser sends whenever You visit our</p>
                <p dir="ltr">Service or when You access the Service by or through a mobile device.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Tracking Technologies and Cookies  </p>
                <p dir="ltr">*********************************</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We use Cookies and similar tracking technologies to track the activity on Our</p>
                <p dir="ltr">Service and store certain information. Tracking technologies used are beacons,</p>
                <p dir="ltr">tags, and scripts to collect and track information and to improve and analyze</p>
                <p dir="ltr">Our Service. The technologies We use may include:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Cookies or Browser Cookies. A cookie is a small file placed on Your</p>
                <p dir="ltr">    Device. You can instruct Your browser to refuse all Cookies or to indicate</p>
                <p dir="ltr">    when a Cookie is being sent. However, if You do not accept Cookies, You</p>
                <p dir="ltr">    may not be able to use some parts of our Service. Unless you have adjusted</p>
                <p dir="ltr">    Your browser setting so that it will refuse Cookies, our Service may use</p>
                <p dir="ltr">    Cookies.</p>
                <p dir="ltr">  * Web Beacons. Certain sections of our Service and our emails may contain</p>
                <p dir="ltr">    small electronic files known as web beacons (also referred to as clear</p>
                <p dir="ltr">    gifs, pixel tags, and single-pixel gifs) that permit the Company, for</p>
                <p dir="ltr">    example, to count users who have visited those pages or opened an email</p>
                <p dir="ltr">    and for other related website statistics (for example, recording the</p>
                <p dir="ltr">    popularity of a certain section and verifying system and server</p>
                <p dir="ltr">    integrity).</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on</p>
                <p dir="ltr">Your personal computer or mobile device when You go offline, while Session</p>
                <p dir="ltr">Cookies are deleted as soon as You close Your web browser. You can learn more</p>
                <p dir="ltr">about cookies on [TermsFeed</p>
                <p dir="ltr">website](https://www.termsfeed.com/blog/cookies/#What_Are_Cookies) article.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Necessary / Essential Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Type: Session Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Administered by: Us</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Purpose: These Cookies are essential to provide You with services</p>
                <p dir="ltr">    available through the Website and to enable You to use some of its</p>
                <p dir="ltr">    features. They help to authenticate users and prevent fraudulent use of</p>
                <p dir="ltr">    user accounts. Without these Cookies, the services that You have asked for</p>
                <p dir="ltr">    cannot be provided, and We only use these Cookies to provide You with</p>
                <p dir="ltr">    those services.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Cookies Policy / Notice Acceptance Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Type: Persistent Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Administered by: Us</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Purpose: These Cookies identify if users have accepted the use of cookies</p>
                <p dir="ltr">    on the Website.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Functionality Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Type: Persistent Cookies</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Administered by: Us</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">    Purpose: These Cookies allow us to remember choices You make when You use</p>
                <p dir="ltr">    the Website, such as remembering your login details or language</p>
                <p dir="ltr">    preference. The purpose of these Cookies is to provide You with a more</p>
                <p dir="ltr">    personal experience and to avoid You having to re-enter your preferences</p>
                <p dir="ltr">    every time You use the Website.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">For more information about the cookies we use and your choices regarding</p>
                <p dir="ltr">cookies, please visit our Cookies Policy or the Cookies section of our Privacy</p>
                <p dir="ltr">Policy.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Use of Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The Company may use Personal Data for the following purposes:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * To provide and maintain our Service , including to monitor the usage of</p>
                <p dir="ltr">    our Service.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * To manage Your Account: to manage Your registration as a user of the</p>
                <p dir="ltr">    Service. The Personal Data You provide can give You access to different</p>
                <p dir="ltr">    functionalities of the Service that are available to You as a registered</p>
                <p dir="ltr">    user.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * For the performance of a contract: the development, compliance and</p>
                <p dir="ltr">    undertaking of the purchase contract for the products, items or services</p>
                <p dir="ltr">    You have purchased or of any other contract with Us through the Service.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * To contact You: To contact You by email, telephone calls, SMS, or other</p>
                <p dir="ltr">    equivalent forms of electronic communication, such as a mobile</p>
                <p dir="ltr">    application's push notifications regarding updates or informative</p>
                <p dir="ltr">    communications related to the functionalities, products or contracted</p>
                <p dir="ltr">    services, including the security updates, when necessary or reasonable for</p>
                <p dir="ltr">    their implementation.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * To provide You with news, special offers and general information about</p>
                <p dir="ltr">    other goods, services and events which we offer that are similar to those</p>
                <p dir="ltr">    that you have already purchased or enquired about unless You have opted</p>
                <p dir="ltr">    not to receive such information.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * To manage Your requests: To attend and manage Your requests to Us.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * For business transfers: We may use Your information to evaluate or conduct</p>
                <p dir="ltr">    a merger, divestiture, restructuring, reorganization, dissolution, or</p>
                <p dir="ltr">    other sale or transfer of some or all of Our assets, whether as a going</p>
                <p dir="ltr">    concern or as part of bankruptcy, liquidation, or similar proceeding, in</p>
                <p dir="ltr">    which Personal Data held by Us about our Service users is among the assets</p>
                <p dir="ltr">    transferred.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * For other purposes : We may use Your information for other purposes, such</p>
                <p dir="ltr">    as data analysis, identifying usage trends, determining the effectiveness</p>
                <p dir="ltr">    of our promotional campaigns and to evaluate and improve our Service,</p>
                <p dir="ltr">    products, services, marketing and your experience.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We may share Your personal information in the following situations:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * With Service Providers: We may share Your personal information with</p>
                <p dir="ltr">    Service Providers to monitor and analyze the use of our Service, to</p>
                <p dir="ltr">    contact You.</p>
                <p dir="ltr">  * For business transfers: We may share or transfer Your personal information</p>
                <p dir="ltr">    in connection with, or during negotiations of, any merger, sale of Company</p>
                <p dir="ltr">    assets, financing, or acquisition of all or a portion of Our business to</p>
                <p dir="ltr">    another company.</p>
                <p dir="ltr">  * With Affiliates: We may share Your information with Our affiliates, in</p>
                <p dir="ltr">    which case we will require those affiliates to honor this Privacy Policy.</p>
                <p dir="ltr">    Affiliates include Our parent company and any other subsidiaries, joint</p>
                <p dir="ltr">    venture partners or other companies that We control or that are under</p>
                <p dir="ltr">    common control with Us.</p>
                <p dir="ltr">  * With business partners: We may share Your information with Our business</p>
                <p dir="ltr">    partners to offer You certain products, services or promotions.</p>
                <p dir="ltr">  * With other users: when You share personal information or otherwise</p>
                <p dir="ltr">    interact in the public areas with other users, such information may be</p>
                <p dir="ltr">    viewed by all users and may be publicly distributed outside.</p>
                <p dir="ltr">  * With Your consent : We may disclose Your personal information for any</p>
                <p dir="ltr">    other purpose with Your consent.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Retention of Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The Company will retain Your Personal Data only for as long as is necessary</p>
                <p dir="ltr">for the purposes set out in this Privacy Policy. We will retain and use Your</p>
                <p dir="ltr">Personal Data to the extent necessary to comply with our legal obligations</p>
                <p dir="ltr">(for example, if we are required to retain your data to comply with applicable</p>
                <p dir="ltr">laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The Company will also retain Usage Data for internal analysis purposes. Usage</p>
                <p dir="ltr">Data is generally retained for a shorter period of time, except when this data</p>
                <p dir="ltr">is used to strengthen the security or to improve the functionality of Our</p>
                <p dir="ltr">Service, or We are legally obligated to retain this data for longer time</p>
                <p dir="ltr">periods.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Transfer of Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Your information, including Personal Data, is processed at the Company's</p>
                <p dir="ltr">operating offices and in any other places where the parties involved in the</p>
                <p dir="ltr">processing are located. It means that this information may be transferred to —</p>
                <p dir="ltr">and maintained on — computers located outside of Your state, province, country</p>
                <p dir="ltr">or other governmental jurisdiction where the data protection laws may differ</p>
                <p dir="ltr">than those from Your jurisdiction.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Your consent to this Privacy Policy followed by Your submission of such</p>
                <p dir="ltr">information represents Your agreement to that transfer.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The Company will take all steps reasonably necessary to ensure that Your data</p>
                <p dir="ltr">is treated securely and in accordance with this Privacy Policy and no transfer</p>
                <p dir="ltr">of Your Personal Data will take place to an organization or a country unless</p>
                <p dir="ltr">there are adequate controls in place including the security of Your data and</p>
                <p dir="ltr">other personal information.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Delete Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">You have the right to delete or request that We assist in deleting the</p>
                <p dir="ltr">Personal Data that We have collected about You.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Our Service may give You the ability to delete certain information about You</p>
                <p dir="ltr">from within the Service.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">You may update, amend, or delete Your information at any time by signing in to</p>
                <p dir="ltr">Your Account, if you have one, and visiting the account settings section that</p>
                <p dir="ltr">allows you to manage Your personal information. You may also contact Us to</p>
                <p dir="ltr">request access to, correct, or delete any personal information that You have</p>
                <p dir="ltr">provided to Us.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Please note, however, that We may need to retain certain information when we</p>
                <p dir="ltr">have a legal obligation or lawful basis to do so.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Disclosure of Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Business Transactions  </p>
                <p dir="ltr">*********************</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">If the Company is involved in a merger, acquisition or asset sale, Your</p>
                <p dir="ltr">Personal Data may be transferred. We will provide notice before Your Personal</p>
                <p dir="ltr">Data is transferred and becomes subject to a different Privacy Policy.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Law enforcement  </p>
                <p dir="ltr">***************</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Under certain circumstances, the Company may be required to disclose Your</p>
                <p dir="ltr">Personal Data if required to do so by law or in response to valid requests by</p>
                <p dir="ltr">public authorities (e.g. a court or a government agency).</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Other legal requirements  </p>
                <p dir="ltr">************************</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The Company may disclose Your Personal Data in the good faith belief that such</p>
                <p dir="ltr">action is necessary to:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">  * Comply with a legal obligation</p>
                <p dir="ltr">  * Protect and defend the rights or property of the Company</p>
                <p dir="ltr">  * Prevent or investigate possible wrongdoing in connection with the Service</p>
                <p dir="ltr">  * Protect the personal safety of Users of the Service or the public</p>
                <p dir="ltr">  * Protect against legal liability</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Security of Your Personal Data  </p>
                <p dir="ltr">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">The security of Your Personal Data is important to Us, but remember that no</p>
                <p dir="ltr">method of transmission over the Internet, or method of electronic storage is</p>
                <p dir="ltr">100% secure. While We strive to use commercially acceptable means to protect</p>
                <p dir="ltr">Your Personal Data, We cannot guarantee its absolute security.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Children's Privacy  </p>
                <p dir="ltr">------------------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Our Service does not address anyone under the age of 13. We do not knowingly</p>
                <p dir="ltr">collect personally identifiable information from anyone under the age of 13.</p>
                <p dir="ltr">If You are a parent or guardian and You are aware that Your child has provided</p>
                <p dir="ltr">Us with Personal Data, please contact Us. If We become aware that We have</p>
                <p dir="ltr">collected Personal Data from anyone under the age of 13 without verification</p>
                <p dir="ltr">of parental consent, We take steps to remove that information from Our</p>
                <p dir="ltr">servers.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">If We need to rely on consent as a legal basis for processing Your information</p>
                <p dir="ltr">and Your country requires consent from a parent, We may require Your parent's</p>
                <p dir="ltr">consent before We collect and use that information.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Links to Other Websites  </p>
                <p dir="ltr">-----------------------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Our Service may contain links to other websites that are not operated by Us.</p>
                <p dir="ltr">If You click on a third party link, You will be directed to that third party's</p>
                <p dir="ltr">site. We strongly advise You to review the Privacy Policy of every site You</p>
                <p dir="ltr">visit.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We have no control over and assume no responsibility for the content, privacy</p>
                <p dir="ltr">policies or practices of any third party sites or services.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Changes to this Privacy Policy  </p>
                <p dir="ltr">------------------------------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We may update Our Privacy Policy from time to time. We will notify You of any</p>
                <p dir="ltr">changes by posting the new Privacy Policy on this page.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">We will let You know via email and/or a prominent notice on Our Service, prior</p>
                <p dir="ltr">to the change becoming effective and update the "Last updated" date at the top</p>
                <p dir="ltr">of this Privacy Policy.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">You are advised to review this Privacy Policy periodically for any changes.</p>
                <p dir="ltr">Changes to this Privacy Policy are effective when they are posted on this</p>
                <p dir="ltr">page.</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">Contact Us  </p>
                <p dir="ltr">----------</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr">If you have any questions about this Privacy Policy, You can contact us:</p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p>
                <p dir="ltr"><br /></p></div>
        </div>

        <Footer />

    </>
}
